GITHUB_KEY: '64f0f24ed394a2f20496'
GITHUB_SECRET: '665a1cd6e815afe20fb7b0a7b2783ae07580c983'
MIT_ID: ''
MIT_SECRET: ''
GOOGLE_CLIENT_ID: ''
GOOGLE_CLIENT_SECRET: ''

test:
  GITHUB_KEY: ''
  GITHUB_SECRET: ''
